apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./nginx-test

# TODO: Include all the needed services into the kustomization
#  - service.yaml
#  - configmap.yaml
#  - ingress.yaml

labels:
  - pairs:
      app: webapp
      managed-by: argocd
