apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-test-ingress
spec:
  rules:
  - http:
      paths:
      - path: /dev/
        pathType: Prefix
        backend:
          service: 
            name: dev-nginx-test-service
            port:
              number: 80
              
